var dataHetSlimsteKindVan2014 = {
	titel: 'Het slimste kind van 2014',
	drieZesNegen: {
		links: {
			vraag3:  'slimsteKindVan2014/driezesnegen/dobus_vraag.mp3',
			vraag6:  'slimsteKindVan2014/driezesnegen/spin.html',
			vraag15:  'slimsteKindVan2014/driezesnegen/kip-konijn.html'
		}
	},
	galerijen:[
	       	{baseUrl:'slimsteKindVan2014/galerij/beroepen/',
	       	 fotos:[
	       		{url:'bakker.jpg',verticaleFoto: true},
	       		{url:'bouwvakker.jpg',verticaleFoto: true},
	       		{url:'brandweerman.jpg',verticaleFoto: true},
	       		{url:'conducteur.jpg',verticaleFoto: true},
	       		{url:'dokter.jpg',verticaleFoto: true},
	       		{url:'fietsenmaker.jpg',verticaleFoto: false},
	       		{url:'kapper.jpg',verticaleFoto: true},
	       		{url:'kok.jpg',verticaleFoto: true},
	       		{url:'piloot.jpg',verticaleFoto: false},
	       		{url:'politieagent.jpg',verticaleFoto: true}]},
	       	{baseUrl:'slimsteKindVan2014/galerij/boerderij/',
	       	 fotos:[
	       		{url:'eend.jpg',verticaleFoto: true},
	       		{url:'ezel.jpg',verticaleFoto: true},
	       		{url:'geit.jpg',verticaleFoto: true},
	       		{url:'kip.jpg',verticaleFoto: true},
	       		{url:'koe.jpg',verticaleFoto: true},
	       		{url:'lama.jpg',verticaleFoto: true},
	       		{url:'paard.jpg',verticaleFoto: true},
	       		{url:'schaap.jpg',verticaleFoto: true},
	       		{url:'struisvogel.jpg',verticaleFoto: true},
	       		{url:'varken.jpg',verticaleFoto: true}]},
	       	{baseUrl:'slimsteKindVan2014/galerij/dieren/',
	       	 fotos:[
	       		{url:'arend.jpg',verticaleFoto: true},
	       		{url:'beer.jpg',verticaleFoto: true},
	       		{url:'chimpansee.jpg',verticaleFoto: true},
	       		{url:'giraf.jpg',verticaleFoto: true},
	       		{url:'leeuw.jpg',verticaleFoto: true},
	       		{url:'neushoorn.jpg',verticaleFoto: true},
	       		{url:'olifant.jpg',verticaleFoto: true},
	       		{url:'tijger.jpg',verticaleFoto: true},
	       		{url:'uil.jpg',verticaleFoto: true},
	       		{url:'zebra.jpg',verticaleFoto: true}]},
	       	{baseUrl:'slimsteKindVan2014/galerij/disney/',
	       	 fotos:[
	       		{url:'bambi.jpg',verticaleFoto: true},
	       		{url:'donald_duck.jpg',verticaleFoto: true},
	       		{url:'kleine_zeemeermin.jpg',verticaleFoto: true},
	       		{url:'knabbel_en_babbel.jpg',verticaleFoto: true},
	       		{url:'mickey.jpg',verticaleFoto: false},
	       		{url:'olaf.jpg',verticaleFoto: true},
	       		{url:'pluto.jpg',verticaleFoto: true},
	       		{url:'sneeuwwitje.jpg',verticaleFoto: true},
	       		{url:'tijgetje.jpg',verticaleFoto: true},
	       		{url:'winnie.jpg',verticaleFoto: true}]},
	       	{baseUrl:'slimsteKindVan2014/galerij/fruit/',
	       	 fotos:[
	       		{url:'ananas.jpg',verticaleFoto: true},
	       		{url:'appel.jpg',verticaleFoto: true},
	       		{url:'banaan.jpg',verticaleFoto: true},
	       		{url:'druiven.jpg',verticaleFoto: true},
	       		{url:'kiwi.jpg',verticaleFoto: true},
	       		{url:'kokosnoot.jpg',verticaleFoto: true},
	       		{url:'mango.jpg',verticaleFoto: true},
	       		{url:'nectarine.jpg',verticaleFoto: false},
	       		{url:'passievrucht.jpg',verticaleFoto: true},
	       		{url:'peer.jpg',verticaleFoto: true}]},
	       	{baseUrl:'slimsteKindVan2014/galerij/groenten/',
	       	 fotos:[
	       		{url:'bloemkool.jpg',verticaleFoto: true},
	       		{url:'broccoli.jpg',verticaleFoto: true},
	       		{url:'erwten.jpg',verticaleFoto: true},
	       		{url:'komkommer.jpg',verticaleFoto: true},
	       		{url:'prei.jpg',verticaleFoto: true},
	       		{url:'rode-kool.jpg',verticaleFoto: true},
	       		{url:'sla.jpg',verticaleFoto: true},
	       		{url:'tomaten.jpg',verticaleFoto: true},
	       		{url:'witloof.jpg',verticaleFoto: true},
	       		{url:'wortelen.jpg',verticaleFoto: true}]},
	       	{baseUrl:'slimsteKindVan2014/galerij/huisdieren/',
	       	 fotos:[
	       		{url:'cavia.jpg',verticaleFoto: true},
	       		{url:'goudvis.jpg',verticaleFoto: true},
	       		{url:'hamster.jpg',verticaleFoto: true},
	       		{url:'hond.jpg',verticaleFoto: true},
	       		{url:'kanaries.jpg',verticaleFoto: true},
	       		{url:'konijn.jpg',verticaleFoto: true},
	       		{url:'muis.jpg',verticaleFoto: false},
	       		{url:'papegaai.jpg',verticaleFoto: false},
	       		{url:'poes.jpg',verticaleFoto: true},
	       		{url:'schildpad.jpg',verticaleFoto: true}]},
	       	{baseUrl:'slimsteKindVan2014/galerij/kleinedieren/',
	       	 fotos:[
	       		{url:'bij.jpg',verticaleFoto: true},
	       		{url:'kikker.jpg',verticaleFoto: true},
	       		{url:'lieveheersbeestje.jpg',verticaleFoto: true},
	       		{url:'mieren.jpg',verticaleFoto: true},
	       		{url:'rups.jpg',verticaleFoto: true},
	       		{url:'slak.jpg',verticaleFoto: true},
	       		{url:'spin.jpg',verticaleFoto: true},
	       		{url:'sprinkhaan.jpg',verticaleFoto: true},
	       		{url:'vlieg2.jpg',verticaleFoto: true},
	       		{url:'vlinder.jpg',verticaleFoto: true}]},
	       	{baseUrl:'slimsteKindVan2014/galerij/sommen/',
	       	 fotos:[
	       		{url:'achtPlus9.png',verticaleFoto: false},
	       		{url:'driePlus4en.png',verticaleFoto: false},
	       		{url:'eenPlusEen.png',verticaleFoto: false},
	       		{url:'negenPlus6.png',verticaleFoto: false},
	       		{url:'tweePlusEen.png',verticaleFoto: false},
	       		{url:'vierPlus2en.png',verticaleFoto: false},
	       		{url:'vijfPlus8en.png',verticaleFoto: false},
	       		{url:'vijfPlusTwee.png',verticaleFoto: false},
	       		{url:'zesPlus3en.png',verticaleFoto: false},
	       		{url:'zevenPlus4.png',verticaleFoto: false}]},
	       	{baseUrl:'slimsteKindVan2014/galerij/sport/',
	       	 fotos:[
	       		{url:'basketball.jpg',verticaleFoto: false},
	       		{url:'korfbal.jpg',verticaleFoto: false},
	       		{url:'lopen.jpg',verticaleFoto: false},
	       		{url:'squash.jpg',verticaleFoto: true},
	       		{url:'tennis.jpg',verticaleFoto: false},
	       		{url:'turnen.jpg',verticaleFoto: false},
	       		{url:'voetbal.jpg',verticaleFoto: true},
	       		{url:'volleybal.jpg',verticaleFoto: true},
	       		{url:'wielrennen.jpg',verticaleFoto: true},
	       		{url:'zwemmen.jpg',verticaleFoto: false}]},
	       	{baseUrl:'slimsteKindVan2014/galerij/sprookjescamping/',
	       	 fotos:[
	       		{url:'botterbaas.jpg',verticaleFoto: true},
	       		{url:'buddy.jpg',verticaleFoto: true},
	       		{url:'bumpie.jpg',verticaleFoto: true},
	       		{url:'droesem.jpg',verticaleFoto: true},
	       		{url:'hannah.jpg',verticaleFoto: true},
	       		{url:'kabor.jpg',verticaleFoto: false},
	       		{url:'lodewijk.jpg',verticaleFoto: true},
	       		{url:'maartje.jpg',verticaleFoto: true},
	       		{url:'tati.jpg',verticaleFoto: true},
	       		{url:'wanda.jpg',verticaleFoto: true}]},
	       	{baseUrl:'slimsteKindVan2014/galerij/studio100/',
	       	 fotos:[
	       		{url:'bobo.jpg',verticaleFoto: true},
	       		{url:'dobus.jpg',verticaleFoto: true},
	       		{url:'lui.jpg',verticaleFoto: false},
	       		{url:'maya.jpg',verticaleFoto: true},
	       		{url:'mega-mindy.jpg',verticaleFoto: true},
	       		{url:'piet_piraat.jpg',verticaleFoto: true},
	       		{url:'plop.jpg',verticaleFoto: false},
	       		{url:'rox.jpg',verticaleFoto: true},
	       		{url:'samson.jpg',verticaleFoto: false},
	       		{url:'wickie.jpg',verticaleFoto: false}]},
	       	{baseUrl:'slimsteKindVan2014/galerij/zeedieren/',
	       	 fotos:[
	       		{url:'dolfijn.jpg',verticaleFoto: true},
	       		{url:'haai.jpg',verticaleFoto: true},
	       		{url:'inktvis.jpg',verticaleFoto: true},
	       		{url:'kreeft.jpg',verticaleFoto: false},
	       		{url:'kwal.jpg',verticaleFoto: false},
	       		{url:'orca.jpg',verticaleFoto: false},
	       		{url:'pinguins.jpeg',verticaleFoto: false},
	       		{url:'schildpad.jpg',verticaleFoto: true},
	       		{url:'walvis.jpg',verticaleFoto: false},
	       		{url:'zeehond.jpg',verticaleFoto: true}]}],
	opendeur: {
		vragen: [
		{urlFoto:'slimsteKindVan2014/opendeur/todo.jpg', urlFilm: 'slimsteKindVan2014/opendeur/todo.mp4', 
		 antwoorden: ['TODO', 'TODO', 'TODO', 'TODO'],
		 link: 'slimsteKindVan2014/opendeur/something.jpg'},
		{urlFoto:'slimsteKindVan2014/opendeur/todo.jpg', urlFilm: 'slimsteKindVan2014/opendeur/todo.mp4', 
		 antwoorden: ['TODO', 'TODO', 'TODO', 'TODO']},
		{naam: 'Omschrijving 3', urlFoto:'slimsteKindVan2014/opendeur/todo.jpg', urlFilm: 'slimsteKindVan2014/opendeur/todo.mp4', 
		 antwoorden: ['TODO', 'TODO', 'TODO', 'TODO']}
		 ]
	},
	puzzels: [
	],
	collectiefGeheugen: {
		videos: [
			{urlVideo: 'slimsteKindVan2014/collectiefgeheugen/Collectief_Geheugen_1.mp4', antwoorden: ['TODO', 'TODO', 'TODO', 'TODO', 'TODO'] },
			{urlVideo: 'slimsteKindVan2014/collectiefgeheugen/Collectief_Geheugen_2.mp4', antwoorden: ['TODO', 'TODO', 'TODO', 'TODO', 'TODO'] },
			{urlVideo: 'slimsteKindVan2014/collectiefgeheugen/Collectief_Geheugen_3.mp4', antwoorden: ['TODO', 'TODO', 'TODO', 'TODO', 'TODO'] }
		],
	},
	finale: [
		{ vraag: 'TODO',
		  antwoorden: ['TODO', 'TODO', 'TODO', 'TODO', 'TODO'] }
	]
};
